# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  options = {
    mount_linux_data.enable = lib.mkEnableOption "Mount LINUX_DATA";
    mount_k8s.enable = lib.mkEnableOption "Mount k8s nfs disk";
  };

  config = {

    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      {
        device = "/dev/disk/by-uuid/377bb05d-554c-47a9-a0f6-3f0f031ab228";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      {
        device = "/dev/disk/by-uuid/49BC-6054";
        fsType = "vfat";
      };

    swapDevices =
      [{ device = "/dev/disk/by-uuid/08ac8672-b5c0-4069-9871-fdef86d7250a"; }];

    fileSystems."/mnt/titan-linux-disk" =
      {
        device = "/dev/disk/by-uuid/3772ace1-c7f0-4924-b65a-d81b046f32c0";
        fsType = "ext4";
      };

    fileSystems."/media/robert/LINUX_DATA" = lib.mkIf config.mount_linux_data.enable
      {
        device = "/dev/disk/by-uuid/b5e50622-9d25-464a-98c9-346cc0e319f6";
        fsType = "ext4";
      };

    # littlelinux
    fileSystems."/mnt/k8s" = lib.mkIf config.mount_k8s.enable
      {
        device = "100.81.249.52:/mnt/DB_DISK/podwriter_k8s_nfs";
        fsType = "nfs";
        options = [ "x-systemd.automount" "noauto" ];
        # options = [ "x-systemd.automount" "noauto" "x-systemd.idle-timeout=600" ];
      };

    networking.useDHCP = lib.mkDefault true;
    networking.interfaces.eno2.wakeOnLan.enable = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    # Bootloader.
    boot.loader.systemd-boot.enable = true;
    boot.loader.efi.canTouchEfiVariables = true;
  };

}
